version: "3.9"   
services:
  hanabot:
    build: 
      dockerfile: Dockerfile_nvidia
    restart: unless-stopped
    environment:
      - TOKEN=""
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             device_ids: ['0']
             capabilities: [compute,utility,video]
             
### Another example
  monnibot:
    build: 
      dockerfile: Dockerfile_nvidia
    restart: unless-stopped
    environment:
      - TOKEN=""
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             device_ids: ['0']
             capabilities: [compute,utility,video]
